run:
  timeout: 5m
  tests: true

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - copyloopvar
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  mnd:
    checks:
      - argument
      - case
      - condition
      - return
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  funlen:
    lines: 80
    statements: 60

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - errcheck
        - funlen
        - gocyclo
        - goconst
        - gocritic
        - gosec
        - mnd
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    - path: cmd/
      linters:
        - gochecknoinits
    - linters:
        - gocritic
      text: "ifElseChain|singleCaseSwitch"
    - linters:
        - gosec
      text: "G204"  # Subprocess launched with variable
    - linters:
        - revive
      text: "unused-parameter"
    - linters:
        - gocritic
      text: "octalLiteral"
    - linters:
        - revive
      text: "func name will be used as detect.DetectPackageManager by other packages"
    - linters:
        - revive
      text: "type name will be used as git.GitError by other packages"