package cmd

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/sotarok/gw/internal/git"
	"github.com/spf13/cobra"
)

var (
	shellIntegrationShowScript bool
	shellIntegrationShell      string
	shellIntegrationPrintPath  string
)

var shellIntegrationCmd = &cobra.Command{
	Use:   "shell-integration",
	Short: "Shell integration utilities",
	Long: `Shell integration utilities for gw.

Use --show-script to output shell integration code that can be eval'd:
  eval "$(gw shell-integration --show-script --shell=zsh)"

Use --print-path to get the worktree path for a specific issue or branch:
  cd $(gw shell-integration --print-path=123)`,
	RunE: runShellIntegration,
}

func init() {
	shellIntegrationCmd.Flags().BoolVar(&shellIntegrationShowScript, "show-script", false, "Output shell integration script")
	shellIntegrationCmd.Flags().StringVar(&shellIntegrationShell, "shell", "", "Shell type (bash, zsh, fish). Auto-detected if not specified")
	shellIntegrationCmd.Flags().StringVar(&shellIntegrationPrintPath, "print-path", "",
		"Print worktree path for the specified issue or branch")
	rootCmd.AddCommand(shellIntegrationCmd)
}

func runShellIntegration(cmd *cobra.Command, args []string) error {
	deps := DefaultDependencies()
	shellCmd := NewShellIntegrationCommand(deps.Git, os.Stdout, os.Stderr)
	shellCmd.showScript = shellIntegrationShowScript
	shellCmd.shell = shellIntegrationShell
	shellCmd.printPath = shellIntegrationPrintPath
	return shellCmd.Execute()
}

// ShellIntegrationCommand handles the shell-integration command logic
type ShellIntegrationCommand struct {
	git        git.Interface
	stdout     io.Writer
	stderr     io.Writer
	showScript bool
	shell      string
	printPath  string
}

// NewShellIntegrationCommand creates a new shell integration command handler
func NewShellIntegrationCommand(gitClient git.Interface, stdout, stderr io.Writer) *ShellIntegrationCommand {
	return &ShellIntegrationCommand{
		git:    gitClient,
		stdout: stdout,
		stderr: stderr,
	}
}

// Execute runs the shell integration command
func (c *ShellIntegrationCommand) Execute() error {
	// Validate flags
	if !c.showScript && c.printPath == "" {
		return fmt.Errorf("either --show-script or --print-path must be specified")
	}
	if c.showScript && c.printPath != "" {
		return fmt.Errorf("cannot use both --show-script and --print-path")
	}

	if c.showScript {
		return c.showShellScript()
	}

	return c.printWorktreePath()
}

func (c *ShellIntegrationCommand) showShellScript() error {
	// Auto-detect shell if not specified
	shell := c.shell
	if shell == "" {
		shell = c.detectShell()
	}

	// Validate shell
	switch shell {
	case shellBash, shellZsh:
		fmt.Fprint(c.stdout, c.getBashZshScript(shell))
	case shellFish:
		fmt.Fprint(c.stdout, c.getFishScript())
	default:
		return fmt.Errorf("unsupported shell: %s (supported: bash, zsh, fish)", shell)
	}

	return nil
}

func (c *ShellIntegrationCommand) detectShell() string {
	// First try SHELL environment variable
	shellPath := os.Getenv("SHELL")
	shell := filepath.Base(shellPath)

	switch {
	case strings.Contains(shell, shellZsh):
		return shellZsh
	case strings.Contains(shell, shellBash):
		return shellBash
	case strings.Contains(shell, shellFish):
		return shellFish
	default:
		// Default to bash if we can't detect
		return shellBash
	}
}

func (c *ShellIntegrationCommand) getBashZshScript(shell string) string {
	shebang := "#!/bin/bash"
	if shell == shellZsh {
		shebang = "#!/bin/zsh"
	}

	script := fmt.Sprintf(`%s
# gw shell integration
# This script is dynamically generated by 'gw shell-integration --show-script'
# Add to your shell configuration with: eval "$(gw shell-integration --show-script --shell=%s)"

gw() {
    # Check if we should auto-cd after command
    if [[ "$1" == "start" || "$1" == "checkout" ]] && [[ -f ~/.gwrc ]]; then
        # Check if auto_cd is enabled
        if grep -q "auto_cd = true" ~/.gwrc 2>/dev/null; then
            # Run the actual command (output goes directly to terminal)
            command gw "$@"
            local exit_code=$?

            # If command succeeded, get the worktree path and cd to it
            if [[ $exit_code -eq 0 ]]; then
                local identifier="${2:-}"  # Get issue number or branch name
                if [[ -n "$identifier" ]]; then
                    # Get the worktree path using shell-integration command
                    local worktree_path=$(command gw shell-integration --print-path="$identifier" 2>/dev/null)

                    # If we got a path, cd to it
                    if [[ -n "$worktree_path" && -d "$worktree_path" ]]; then
                        cd "$worktree_path"
                        echo "Changed directory to: $worktree_path"
                    fi
                fi
            fi

            return $exit_code
        else
            # Auto CD disabled, just run the command normally
            command gw "$@"
        fi
    else
        # Not a start/checkout command, just run normally
        command gw "$@"
    fi
}
`, shebang, shell)

	if shell == shellZsh {
		script += `
# gw zsh completion
_gw() {
    local -a subcmds
    subcmds=(
        'start:Create a new worktree for the specified issue or branch'
        'end:Remove a worktree for the specified issue'
        'checkout:Checkout an existing branch as a new worktree'
        'clean:Remove all safely deletable worktrees'
        'init:Initialize gw configuration'
        'shell-integration:Shell integration utilities'
    )

    _arguments -C \
        '1:command:->command' \
        '*::arg:->args'

    case "$state" in
        command)
            _describe 'command' subcmds
            ;;
        args)
            case "$words[1]" in
                end)
                    # Complete with worktree branch names
                    local -a branches
                    branches=(${(f)"$(git worktree list --porcelain 2>/dev/null | grep '^branch ' | sed 's|^branch refs/heads/||')"})
                    if (( ${#branches} )); then
                        _describe 'worktree branch' branches
                    fi
                    ;;
                checkout)
                    # Complete with remote branch names (strip origin/ prefix)
                    local -a remote_branches
                    remote_branches=(${(f)"$(git branch -r 2>/dev/null | grep -v 'HEAD' | sed 's|^ *origin/||')"})
                    if (( ${#remote_branches} )); then
                        _describe 'remote branch' remote_branches
                    fi
                    ;;
                start)
                    # No completion for issue numbers
                    ;;
            esac
            ;;
    esac
}

compdef _gw gw
`
	}

	return script
}

func (c *ShellIntegrationCommand) getFishScript() string {
	return `#!/usr/bin/env fish
# gw shell integration for Fish
# This script is dynamically generated by 'gw shell-integration --show-script'
# Add to your shell configuration with: gw shell-integration --show-script --shell=fish | source

function gw
    # Check if we should auto-cd after command
    if test "$argv[1]" = "start" -o "$argv[1]" = "checkout"
        if test -f ~/.gwrc
            # Check if auto_cd is enabled
            if grep -q "auto_cd = true" ~/.gwrc 2>/dev/null
                # Run the actual command (output goes directly to terminal)
                command gw $argv
                set exit_code $status
                
                # If command succeeded, get the worktree path and cd to it
                if test $exit_code -eq 0
                    set identifier "$argv[2]"  # Get issue number or branch name
                    if test -n "$identifier"
                        # Get the worktree path using shell-integration command
                        set worktree_path (command gw shell-integration --print-path="$identifier" 2>/dev/null)
                        
                        # If we got a path, cd to it
                        if test -n "$worktree_path" -a -d "$worktree_path"
                            cd "$worktree_path"
                            echo "Changed directory to: $worktree_path"
                        end
                    end
                end
                
                return $exit_code
            else
                # Auto CD disabled, just run the command normally
                command gw $argv
            end
        else
            # No config file, just run normally
            command gw $argv
        end
    else
        # Not a start/checkout command, just run normally
        command gw $argv
    end
end
`
}

func (c *ShellIntegrationCommand) printWorktreePath() error {
	if c.printPath == "" {
		return fmt.Errorf("--print-path requires an issue number or branch name")
	}

	// Use the injected git client to find the worktree.
	gitClient := c.git
	if gitClient == nil {
		gitClient = git.NewClient()
	}

	// Check if we're in a git repository
	if !gitClient.IsGitRepository() {
		return fmt.Errorf("not in a git repository")
	}

	// Try to find the worktree path
	worktreePath, err := findWorktreePath(gitClient, c.printPath)
	if err != nil {
		// Don't print error message, just return non-zero exit code
		// Shell function will check exit code
		return err
	}

	// Print only the path
	fmt.Fprintln(c.stdout, worktreePath)
	return nil
}

func findWorktreePath(gitClient git.Interface, identifier string) (string, error) {
	// Get the original repository name (not the worktree directory name) so the
	// expected path matches how worktrees are created — anchored to the repo
	// name — even when this runs from inside an existing worktree.
	repoName, err := gitClient.GetOriginalRepositoryName()
	if err != nil {
		return "", err
	}
	// Anchor the expected worktree lookup to the repository root so that
	// invocations from a sub directory still resolve to the worktree sitting
	// as a sibling of the repo (rather than a sibling of the sub directory).
	repoRoot, err := gitClient.GetRepositoryRoot()
	if err != nil {
		return "", err
	}

	// First, check if the expected directory exists (most common case after 'gw start')
	// This works even if git worktree list hasn't updated yet
	expectedPath := git.ResolveWorktreePath(repoRoot, repoName, identifier)
	if info, err := os.Stat(expectedPath); err == nil && info.IsDir() {
		return expectedPath, nil
	}

	// Next, try to find via git worktree list
	worktrees, err := gitClient.ListWorktrees()
	if err == nil {
		for _, wt := range worktrees {
			// Check for exact branch match
			if wt.Branch == identifier {
				return wt.Path, nil
			}
			// Check if branch matches issue pattern (e.g., "123/impl")
			if strings.HasPrefix(wt.Branch, identifier+"/") {
				return wt.Path, nil
			}
		}
	}

	// If not found as issue, try as branch name (for checkout command)
	sanitizedBranchName := git.SanitizeBranchNameForDirectory(identifier)
	if sanitizedBranchName != identifier {
		expectedPath = git.ResolveWorktreePath(repoRoot, repoName, sanitizedBranchName)
		if info, err := os.Stat(expectedPath); err == nil && info.IsDir() {
			return expectedPath, nil
		}
	}

	return "", fmt.Errorf("worktree not found for: %s", identifier)
}
